apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec: 
  selector:
    app: myapp
    release: beta
  # clusterIP:  10.99.99.99
  # 不声明clusterIP则由 coredns 随分配
  type: NodePort
  ports:
  - port: 80
  # 当前服务端口
    targetPort: 80
  # pod端口
    nodePort: 30080
  # 外部访问端口，集群中的每个节点都可