# pod的存活探测
apiVersion: v1
kind: Pod
metadata:
  name: readiness-httpget-pod
  namespace: default
spec:
  containers:
  - name: readiness-httpget-container
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    # 镜像获取方式
    imagePullPolicy: IfNotPresent
    # 存活探测
    readinessProbe:
    # 探测方式
      httpGet:
        port: http
        path: /index.html
    # 首次探测延迟时间
      initialDelaySeconds: 1
    # 每次探测间隔时间
      periodSeconds: 3

